---
# main tasks file for tomcat 8

#- name: Include tomcat8 variables.
#  include_vars: tomcat8.yml
#  when: tomcat_version | regex_search("^8\.")
  
- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: log4j.yml

- import_tasks: apr.yml
  run_once: yes
  when: tomcat_apr

- import_tasks: check.yml
