---
- name: create  user_group
  group: name={{ rocketmq_group }} state=present

- name: create user
  user: name={{ rocketmq_user }}  groups={{ rocketmq_group }} append=yes

- name: make rocketmq home folder
  file:
    path: "{{rocketmq_home}}"
    state: directory
    owner: "{{rocketmq_user}}"
    group: "{{rocketmq_group}}"

- name: create file 
  file:
    path: /usr/local/rocketmq-console
    state: directory

- name: unarchive rocketmq package
  copy:
    src: "/data/www/software/{{rocketmq_console_jar}}"
    dest: "/usr/local/rocketmq-console"
    owner: "{{rocketmq_user}}"
    group: "{{rocketmq_group}}"

- block:
  - name: template rocketmq console init script
    template: src=rocketmq-console.init.j2 dest=/etc/init.d/rocketmq-console mode=755 owner=root group=root

  - name: enable rocketmq broker start
    service: name=rocketmq-console state=started enabled=yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

