---
# tasks file for install kubelet
- name: copy kubectl execute file
  copy:
    src: server/bin/kubectl
    dest: /usr/bin/
    mode: 0755

- name: kubectl config set
  shell: "{{ item }}"
  with_items:
    - kubectl config set-cluster kubernetes --certificate-authority=/etc/kubernetes/ssl/ca.pem --embed-certs=true --server={{ KUBE_APISERVER }}
    - kubectl config set-credentials admin --client-certificate=/etc/kubernetes/ssl/admin.pem --embed-certs=true --client-key=/etc/kubernetes/ssl/admin-key.pem
    - kubectl config set-context kubernetes --cluster=kubernetes --user=admin
    - kubectl config use-context kubernetes 

